### ISSUE TITLE
unique and/or random strings

### ISSUE THREAD

**Issue by abaird** [bret/model#1]
Provide a way for models to generate differing forms of random strings:

``` ruby
class UserModel < Model
  key(:first) { Faker::Name.first_name }
  key(:last) { Faker::Name.last_name }
  key(:email) { "#{first}.#{last}.#{random(8)}@devnull.com" }
end

it 'should be able to generate a random string on a compound field' do
  user = UserModel.new
  expect(user.email).to match(/#{user.first}\.#{user.last}\+[A-Za-z0-9]{8}@devnull.com/)
end
```

I could write a similar test that injected a unique ID where the implementation is something like:

``` ruby
def unique(num=8)
  UUID.new.generate(:compact)[0..num]
end
```

I can write tests for this if needed, but I don't want to spend the time if you don't like the idea.

Justification:
The need for multiple kinds (random vs. unique) is because you are making an object in a system that needs to be unique. Perhaps just having unique would be enough.

**Comment by titusfortner** [comment]
This is what I was saying in my email. 
I've used this pattern before:

``` Ruby
def new_org_note_model(organization, seed_value=nil)
  seed_value ||= rand(1000)
  OrgNoteModel.new(subject: "subject_#{seed_value}",
                   note: "Note #{seed_value}",
                   org_id: organization.id,
                   author_name: 'foo',
                   author_id: 1)
end 
```

I liked being able to pass in the value so my tests would know about it instead of having it generated in the background... but maybe the model can store the seed separately instead of requiring it to get passed in. Let me do a PR with an idea.

**Comment by bret** [comment]
@titusfortner does this meet your requirements?

``` Ruby
    def OrgNoteModel < Model
      key(:seed) { rand(1000) }
      key(:subject) { "subject_#{seed}"}
      key(:note) { "Note #{seed}"}
    end
```

**Comment by bret** [comment]
@abaird does this meet your requirements?

``` Ruby
class UserModel < Model
  def unique(num=8)
    UUID.new.generate(:compact)[0..num]
  end
  key(:first) { Faker::Name.first_name }
  key(:last) { Faker::Name.last_name }
  key(:email) { "#{first}.#{last}.#{unique}@devnull.com" }
end
```

**Comment by titusfortner** [comment]
Can we make it
`@unique ||= UUID.new.generate(:compact)[0..num]`
and make @unique accessible.
I'm not coming up with an idea use case right now, but there have been times I've wanted to verify the information in the model, but didn't have access to the uuid.

**Comment by bret** [comment]
``` Ruby
class UserModel < Model
  key(:unique){ UUID.new.generate(:compact)[0..8] }
  key(:first) { Faker::Name.first_name }
  key(:last) { Faker::Name.last_name }
  key(:email) { "#{first}.#{last}.#{unique}@devnull.com" }
end
```

**Comment by titusfortner** [comment]
Yes, even better.

**Comment by abaird** [comment]
@bret - that sounds like another way of saying generating randomness is not the Model gem's responsibility  :)  Which, is fine I think unless there is a reason why we would want to initialize a model and have it use a pre-determined unique value. For example, say you wanted a test run id and have all of the model's unique values derived from that id. 
In that case, you could always pass in the value: 

``` ruby
MyModel.new(unique: <value>)
```

rather than having it be part of the framework.

**Comment by bret** [comment]
@abaird Let's not think of this as a framework. It is a library. Currently it has only one class. The best way I can think of meeting your request would be to create this subclass:

``` Ruby
class SeededModel < Model
  key(:seed) { UUID.new.generate(:compact)[0..8] }}
end
```

And then it could be used like this:

``` Ruby
class UserModel < SeededModel
  key(:first) { Faker::Name.first_name }
  key(:last) { Faker::Name.last_name }
  key(:email) { "#{first}.#{last}.#{seed}@devnull.com" }
end
```

If there is agreement on the implementation of the SeededModel, then I am happy to add this subclass to the gem. However, it seems that everyone has their own ideas about the best way to introduce uniqueness/randomness, so maybe this is better as a pattern? I am open to ideas here.

On the other hand, I am trying to create something lightweight. So including this subclass in the gem would mean adding a gem dependency on UUID.

So right now, I am thinking the best thing to do would to be to create a wiki page for this project that shows how to do this.

**Comment by bret** [comment]
Wiki page created: https://github.com/bret/model/wiki/Random-or-Unique-Seeds

**Comment by abaird** [comment]
works for me
