### ISSUE TITLE
Add equality methods

### ISSUE THREAD

**Issue by titusfortner** [bret/model#2]
I make frequent use of the notion of "does the information I entered into the form equal the information I get back out from the API" etc. 

We want a way to compare model instances that doesn't just go off of their location in memory.

**Comment by bret** [comment]
I agree with this request. Please submit a pull request that makes this pass:

``` Ruby
  it 'should know whether two models are equal' do
    user1 = UserModel.new(first: 'Kartik', last: 'Chandran')
    user2 = UserModel.new(first: 'Kartik', last: 'Chandran')
    expect(user1).to eql user2
  end
```
